// songs.js
const songs = [
{
    "title": "Avera: The Multidimensional Plague",
    "genres": "Progressive Rock",
    "spiritualMessage": "Sin as a multidimensional virus infecting humanity, only cured by Christ's sacrifice",
    "spiritualNeeds": " Struggling with sin, need for understanding sin's pervasiveness, desire for redemption",
    "motto": " \"Discover the unseen battle raging within!\"",
    "keywords": " healing, deliverance, freedom, redemption, restoration, cleansing, purification, transformation, renewal, liberation, breakthrough, victory ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75b95cef46462a86876f5/scaled_640.jpg"
  },
  {
    "title": "Avera: The Virus of Sin",
    "genres": "Alternative Rock with Spoken Word elements",
    "spiritualMessage": "Sin as a virus infecting humanity, only cured by Christ's sacrifice and blood",
    "spiritualNeeds": " Battling temptation, need for spiritual cleansing, desire for freedom from sin",
    "motto": " \"The ultimate cure for humanity's deadliest disease!\"",
    "keywords": " cleansing, forgiveness, renewal, restoration, healing, purification, redemption, transformation, liberation, freedom, deliverance, breakthrough ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75a86cef46462a868766d/scaled_640.jpg"
  },
  {
    "title": "Belshazzar's Feast: The Night Babylon Fell",
    "genres": "Dramatic biblical oratorio, opulent choruses, terrified solos, mystical interludes, and prophetic declarations",
    "spiritualMessage": "God judges pride, the folly of defying God, the consequences of sin",
    "spiritualNeeds": " Dealing with pride, need for humility, fear of judgment",
    "motto": " \"Witness the fall of pride and the rise of divine justice!\"",
    "keywords": " consequences, pride, warning, judgment, downfall, hubris, arrogance, divine intervention, accountability, repentance, humility, lesson ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73fb8cef46462a8686c79/scaled_640.jpg"
  },
  {
    "title": "Beyond Arguments",
    "genres": "Alternative Rock, Acoustic Folk elements, introspective vocals, building instrumentation, 72 BPM, male voice",
    "spiritualMessage": "Faith in Jesus goes beyond intellectual arguments; personal encounter with Christ is more powerful than debate; true faith is about a relationship, not just beliefs",
    "spiritualNeeds": "Need for personal experience with God, desire for faith beyond intellectual understanding, seeking genuine encounter with Jesus",
    "motto": "\"Experience the faith that silences doubt!\"",
    "keywords": " experience, relationship, encounter, truth, personal faith, authenticity, transformation, revelation, intimacy, discovery, understanding, conviction ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73ebecef46462a8686c16/scaled_640.jpg"
  },
  {
    "title": "Beyond Religion",
    "genres": "Indie Pop, Catchy hooks, introspective lyrics, blend of acoustic and electronic elements",
    "spiritualMessage": "True faith is a personal relationship with God, not just religious practices",
    "spiritualNeeds": " Disillusioned with religious practices, seeking genuine faith, desire for personal relationship with God",
    "motto": " \"Experience faith beyond rituals!\"",
    "keywords": " authenticity, personal faith, genuine, relationship, intimacy, depth, sincerity, truth, experience, transformation, renewal, revelation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e8625f4ef2856a9219f308/scaled_512.jpg"
  },
  
  {
    "title": "Beyond Tolkien's Tale",
    "genres": "Alternative Rock, Cinematic, Powerful Vocals, Emotional, Electric Guitar, Orchestral Elements",
    "spiritualMessage": "God's love and salvation surpass any fantasy, Jesus is the true hero of reality",
    "spiritualNeeds": " Seeking truth beyond fiction, need for real-world faith, desire for true heroism",
    "motto": " \"Discover the greatest story ever told!\"",
    "keywords": " reality, truth, hero, savior, adventure, journey, destiny, purpose, meaning, revelation, discovery, transformation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73db0cef46462a8686beb/scaled_640.jpg"
  },
  {
    "title": "Blessed Is the Man (Psalm 1 Hymn)",
    "genres": "Uplifting Contemporary Christian, acoustic guitar, warm pads, gentle drums, worship, gospel",
    "spiritualMessage": "Blessings of following God's ways, contrast between righteous and wicked paths",
    "spiritualNeeds": " Seeking guidance, desire for righteousness, need for wisdom",
    "motto": " \"Plant yourself in God's Word and flourish!\"",
    "keywords": " guidance, prosperity, wisdom, choices, righteousness, fulfillment, success, happiness, blessings, fruitfulness, stability, integrity ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e858e64ef2856a9219e887/scaled_512.jpg"
  },
  {
    "title": "Breaking Every Chain",
    "genres": "Epic cinematic, powerful orchestral, triumphant choirs, dramatic crescendo",
    "spiritualMessage": "Jesus breaks every chain, His love transforms lives, He is the answer to all needs",
    "spiritualNeeds": " Feeling bound by circumstances or sin, need for freedom, desire for transformation",
    "motto": " \"Freedom is just one song away!\"",
    "keywords": " freedom, liberation, deliverance, breakthrough, victory, release, empowerment, healing, restoration, transformation, renewal, hope ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e753e3cef46462a86874e8/scaled_640.jpg"
  },
  {
    "title": "Call from Heaven",
    "genres": "Epic Christian rock ballad with powerful vocals, emotional guitar solos, and orchestral elements",
    "spiritualMessage": "Hope in the face of death, God's comfort in loss, eternal life through Christ",
    "spiritualNeeds": " Dealing with grief, seeking comfort in loss, need for eternal perspective",
    "motto": " \"Hear the whisper of eternity!\"",
    "keywords": " loss, grief, comfort, eternal life, hope, reassurance, peace, reunion, healing, purpose, destiny, heavenly perspective ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75866cef46462a86875da/scaled_640.jpg"
  },
  {
    "title": "Choose Life",
    "genres": "Contemporary Christian, Gospel Rock, Christian Pop, Inspirational Rock",
    "spiritualMessage": "Urgency of choosing Christ, eternal consequences of decisions, God's offer of salvation",
    "spiritualNeeds": " At a crossroads, need for direction, desire for meaningful life",
    "motto": " \"Your eternal future hangs in the balance!\"",
    "keywords": " decision, crossroads, destiny, future, purpose, meaning, direction, path, consequences, opportunity, growth, transformation ",
    "playlist": "https://www.youtube.com/watch?v=FoLfWtmY8wY&list=PLck0FjnEKceKhKKQLzOeFTSNZc0FOB0WK",
    "appleMusic": "http://itunes.apple.com/album/id/1765847540",
    "spotify": "https://open.spotify.com/album/57ePpZYkuegugxm2qHHcfR?si=8lJy9Ux4TA-Cfc4pVCRdng",
    "youtube": "https://youtu.be/FoLfWtmY8wY",
    "pageUrl": "https://lionheartrevival.com/choose-life",
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e72e31cef46462a8686576/scaled_640.jpg"
  },
    {
    "title": "Choose to Worship",
    "genres": "Contemporary Worship, Uplifting, Melodic, 72 bpm, male voice",
    "spiritualMessage": "Choosing worship over worry leads to peace; every moment is an opportunity to praise God; gratitude transforms our perspective",
    "spiritualNeeds": "Need for peace in difficult times, desire to overcome anxiety, seeking a positive life outlook",
    "motto": " \"Unlock your divine potential!\"",
    "keywords": "Gratitude, decision, perspective, mindset, attitude, lifestyle, devotion, praise, surrender, choice",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e85f1d4ef2856a9219ef20/scaled_512.jpg"
  },
  {
    "title": "Chosen for Greatness",
    "genres": "Epic Cinematic, Powerful Orchestral, Triumphant Choirs, Dramatic Crescendo",
    "spiritualMessage": "God has a plan for each person, importance of saying yes to God's calling",
    "spiritualNeeds": " Feeling insignificant, need for purpose, desire to understand God's plan",
    "motto": " \"Unlock your divine potential!\"",
    "keywords": " purpose, calling, destiny, potential, significance, impact, influence, mission, anointing, empowerment, divine plan, fulfillment ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e740c9cef46462a8686d39/scaled_640.jpg"
  },
  {
    "title": "Come, Lord Jesus (The Morning Star)",
    "genres": "Modern worship rock, electric guitars, powerful drums, passionate vocals",
    "spiritualMessage": "Longing for Christ's return, Jesus as the Morning Star, living water",
    "spiritualNeeds": " Longing for Christ's return, need for hope in dark times, desire for spiritual fulfillment",
    "motto": " \"Anticipate the ultimate cosmic event!\"",
    "keywords": " hope, anticipation, return, longing, preparation, expectation, renewal, restoration, fulfillment, completion, transformation, reunion ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e859f94ef2856a9219e9bb/scaled_512.jpg"
  },
  {
    "title": "Crna Goro, \u010duj glas",
    "genres": "Majestic Balkan Christian anthem, powerful orchestral arrangement, solemn choral vocals",
    "spiritualMessage": "Call for Montenegro to turn to Christ, repentance, salvation through Jesus",
    "spiritualNeeds": "Need for national spiritual awakening, desire for cultural transformation, seeking God's intervention",
    "motto": " \"Montenegro, your spiritual revolution begins here!\"",
    "keywords": " awakening, repentance, nation, revival, transformation, renewal, restoration, spiritual growth, purpose, destiny, calling, redemption ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73a0acef46462a8686a51/scaled_512.jpg"
  },
  {
    "title": "Crna Goro, \u010duj taj zov",
    "genres": "Majestic Balkan Christian anthem, powerful orchestral arrangement, solemn choral vocals",
    "spiritualMessage": "Urgent call for Montenegro to turn to God, repentance, spiritual awakening",
    "spiritualNeeds": "Urgency for spiritual change, need for national repentance, desire for God's presence",
    "motto": " \"Heed the call that will change a nation!\"",
    "keywords": " urgency, awakening, nation, spiritual renewal, transformation, restoration, repentance, purpose, destiny, calling, redemption, revival ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e8641c4ef2856a9219f5dc/scaled_512.jpg"
  },
  {
    "title": "Crossroads of Eternity",
    "genres": "Progressive Rock, atmospheric synthesizers, powerful guitar riffs, introspective vocals, philosophic",
    "spiritualMessage": "Eternal consequences of choices, importance of following God's path",
    "spiritualNeeds": " Facing major life decisions, need for eternal perspective, desire for divine guidance",
    "motto": " \"Your next step could last forever!\"",
    "keywords": " decisions, consequences, destiny, choices, future, path, direction, purpose, meaning, eternity, accountability, wisdom ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75427cef46462a86874ea/scaled_640.jpg"
  },
  {
    "title": "Cycles of Life",
    "genres": "Contemplative folk rock, acoustic guitar, subtle percussion, haunting vocals",
    "spiritualMessage": "Wisdom in fearing God, recognizing life's cycles, finding meaning in God",
    "spiritualNeeds": " Feeling stuck in life's routines, need for meaning, desire to understand God's ways",
    "motto": " \"Find your place in God's grand design!\"",
    "keywords": " wisdom, meaning, purpose, seasons, growth, change, renewal, perspective, understanding, acceptance, patience, faith ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e857204ef2856a9219e4a4/scaled_512.jpg"
  },
  
  {
    "title": "Divine ABCs (God from A to Z)",
    "genres": "Hip-hop, rhythmic beat, melodic hook, spoken word elements",
    "spiritualMessage": "God's attributes from A to Z, praising God's character",
    "spiritualNeeds": " Seeking to understand God's attributes, desire for comprehensive faith knowledge, need for praise inspiration",
    "motto": " \"Explore God's character from A to Z!\"",
    "keywords": " attributes, character, praise, worship, adoration, revelation, knowledge, understanding, intimacy, relationship, discovery, glory ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75c71cef46462a8687714/scaled_640.jpg"
  },
  {
    "title": "Divine Beat",
    "genres": "Afrobeats, upbeat rhythms, African percussion, melodic hooks, inspirational lyrics, African American",
    "spiritualMessage": "Choosing Christ over worldly pursuits, importance of faith for youth",
    "spiritualNeeds": " Youth seeking purpose, need for faith-based identity, desire to choose God over worldly pursuits",
    "motto": " \"Get your faith on the rhythm!\"",
    "keywords": " youth, choices, purpose, direction, energy, passion, dedication, commitment, future, potential, influence, impact ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75c06cef46462a86876ff/scaled_640.jpg"
  },
  {
    "title": "Don't forget Christ",
    "genres": "hard rock",
    "spiritualMessage": "Returning to Christ when feeling lost, finding peace and new life in Him",
    "spiritualNeeds": " Feeling distant from God, need for spiritual renewal, desire to return to faith",
    "motto": " \"The comeback your soul's been waiting for!\"",
    "keywords": " return, restoration, peace, renewal, remembrance, recommitment, rediscovery, hope, purpose, meaning, healing, transformation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e7550ecef46462a8687512/scaled_640.jpg"
  },
  {
    "title": "Dust on the Bible",
    "genres": "Contemporary Christian Rock, powerful guitars, dynamic drums, emotive vocals, male voice",
    "spiritualMessage": "The Bible is more than a book; it's a path to salvation and spiritual renewal; neglecting it leads to spiritual decay",
    "spiritualNeeds": "Need for spiritual revival, desire to reconnect with God's Word, seeking guidance and truth",
    "motto": "\"Dust off your destiny - it's written in the Book!\"",
    "keywords": " renewal, spiritual growth, guidance, wisdom, rediscovery, recommitment, transformation, revelation, understanding, application, truth, life ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73b24cef46462a8686af1/scaled_640.jpg"
  },
  {
    "title": "Echoes of Tomorrow",
    "genres": "Emotional rock ballad, piano, electric guitar, powerful drums, passionate vocals",
    "spiritualMessage": "Importance of choices, eternal consequences, God's plan for our lives",
    "spiritualNeeds": " Concerned about future, need for hope, desire to make impactful choices",
    "motto": " \"Your choices today echo in eternity!\"",
    "keywords": " future, consequences, destiny, purpose, choices, impact, legacy, eternity, responsibility, wisdom, foresight, preparation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73ff8cef46462a8686ca7/scaled_640.jpg"
  },
  {
    "title": "Eternity's Call",
    "genres": "Christian Rock, Contemporary Christian, Gospel Rock Alternative Christian, Worship Rock",
    "spiritualMessage": "Urgency of salvation, eternal consequences, choosing Christ",
    "spiritualNeeds": " Feeling the urgency of life choices, need for eternal perspective, desire for salvation",
    "motto": " \"Answer the call that transcends time!\"",
    "keywords": " urgency, decision, eternity, salvation, choice, destiny, future, consequences, opportunity, transformation, redemption, hope ",
    "playlist": "https://www.youtube.com/watch?v=NA80dYZHVGY&list=PLck0FjnEKceKhKKQLzOeFTSNZc0FOB0WK",
    "appleMusic": "https://music.apple.com/me/album/eternitys-call-single/1763615940",
    "spotify": "https://open.spotify.com/track/3BMeTVJxPKKwd3bkCbVZGU",
    "youtube": "https://youtu.be/eiF213fDWjo",
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e724d5cef46462a8685fa5/scaled_640.jpg",
    "pageUrl": "https://lionheartrevival.com/eternity-s-call" 

  },
  {
    "title": "Eternal Choices",
    "genres": "Christian Hip-Hop, hard-hitting beats, spoken word elements, urgent tone",
    "spiritualMessage": "Urgency of choosing Christ, eternal consequences of decisions",
    "spiritualNeeds": " Facing life-changing decisions, need for eternal perspective, desire for divine guidance",
    "motto": " \"Choose now, cherish forever!\"",
    "keywords": " decisions, consequences, eternity, destiny, future, path, direction, purpose, meaning, responsibility, wisdom, accountability ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73700cef46462a86868c9/scaled_640.jpg"
  },
  {
    "title": "Eternal Hallelujah",
    "genres": "A cappella, Gospel-inspired, Reverent, Joyful",
    "spiritualMessage": "Praising God's eternal nature, His worthiness of worship",
    "spiritualNeeds": " Need for joy in worship, desire to praise God, seeking eternal perspective",
    "motto": " \"Join the never-ending chorus!\"",
    "keywords": " worship, praise, joy, gratitude, adoration, celebration, exaltation, glory, honor, thanksgiving, reverence, devotion ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e860834ef2856a9219f0ed/scaled_512.jpg"
  },
  {
    "title": "Eternal Praise",
    "genres": "Gospel, Pop, Soul, New-age, R&B, Ballad, Contemporary, Acoustic, Chillout, Inspiring",
    "spiritualMessage": "Praising God's eternal nature, His worthiness of worship",
    "spiritualNeeds": " Desire to worship, need for focus on God's eternal nature, seeking joy in praise",
    "motto": " \"Elevate your worship to timeless heights!\"",
    "keywords": " worship, adoration, glory, gratitude, exaltation, honor, reverence, thanksgiving, celebration, devotion, praise, joy ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e85ba04ef2856a9219eb64/scaled_512.jpg"
  },
  {
    "title": "Eternal Throne",
    "genres": "Epic Worship, powerful piano, driving drums, build to majestic chorus, New-age, R&B, Ballad",
    "spiritualMessage": "God's eternal reign, worthiness of worship, call to praise",
    "spiritualNeeds": " Seeking stability in changing world, need for assurance of God's reign, desire to worship",
    "motto": " \"Bow before the King of endless days!\"",
    "keywords": " sovereignty, majesty, worship, praise, authority, power, reign, glory, honor, reverence, adoration, exaltation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73a5ecef46462a8686a70/scaled_640.jpg"
  },
  {
    "title": "Eternity Calling",
    "genres": "Hip-Hop, trap, Rhythmic spoken word, electronic beats, urgent tone, repetitive hooks",
    "spiritualMessage": "Urgency of salvation, eternal consequences, choosing Christ",
    "spiritualNeeds": " Feeling the urgency of spiritual matters, need for eternal perspective, desire for salvation",
    "motto": " \"Pick up - it's the most important call of your life!\"",
    "keywords": " urgency, decision, destiny, salvation, choice, future, consequences, opportunity, transformation, redemption, hope, eternity ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73942cef46462a868698e/scaled_640.jpg"
  },
  
  {
    "title": "Eyes on Heaven",
    "genres": "Alternative Rock, Worship elements, driving guitars, emotive vocals",
    "spiritualMessage": "Focusing on God amidst worldly chaos, finding peace in Christ",
    "spiritualNeeds": " Overwhelmed by world events, need for focus on God, desire for peace amidst chaos",
    "motto": " \"Lift your gaze to eternal horizons!\"",
    "keywords": " focus, peace, perspective, hope, purpose, direction, clarity, assurance, comfort, strength, guidance, eternity ",
    "playlist": "https://www.youtube.com/watch?v=NA80dYZHVGY&list=PLck0FjnEKceKhKKQLzOeFTSNZc0FOB0WK",
    "appleMusic": "https://music.apple.com/us/album/eyes-on-heaven-single/1766768127",
    "spotify": "https://open.spotify.com/album/1qfprMY61IGFaHgW8bokhO",
    "youtube": "https://youtu.be/ZNaI2ClN2d0",
    "pageUrl": "https://lionheartrevival.com/eyes-on-heaven",
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75ecccef46462a86877c7/scaled_640.jpg"
  },
  {
    "title": "Faithful Like Paul",
    "genres": "Christian Rock, Rock Ballad, Epic Rock, Inspirational Rock, Contemporary Christian",
    "spiritualMessage": "Encouragement to remain faithful like the Apostle Paul, enduring trials for Christ",
    "spiritualNeeds": " Need for perseverance, facing trials, desire to remain strong in faith",
    "motto": " \"Endure like a spiritual champion!\"",
    "keywords": " perseverance, endurance, commitment, loyalty, dedication, steadfastness, courage, conviction, passion, purpose, mission, legacy ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e8556d4ef2856a9219e166/scaled_512.jpg"
  },
  {
    "title": "False Peace",
    "genres": "Industrial trap, distorted synths, hard-hitting beats, intense vocals",
    "spiritualMessage": "Danger of false peace with God, need for true repentance and reconciliation",
    "spiritualNeeds": " Complacent in faith, need for genuine relationship with God, desire for true peace",
    "motto": " \"Shatter the illusion, embrace true peace!\"",
    "keywords": " deception, truth, reconciliation, genuine peace, discernment, authenticity, reality, awakening, confrontation, honesty, transformation, true peace ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e7554ccef46462a8687520/scaled_640.jpg"
  },
  {
    "title": "Fire from Heaven: Elijah on Mount Carmel",
    "genres": "Biblical epic oratorio, dramatic contrasts, powerful solos, and triumphant choral pieces",
    "spiritualMessage": "God's power over false gods, importance of true faith",
    "spiritualNeeds": " Doubting God's power, need for faith in difficult circumstances, desire for God to show Himself",
    "motto": " \"Witness the ultimate spiritual showdown!\"",
    "keywords": " power, faith, challenge, victory, confrontation, divine intervention, courage, conviction, truth, vindication, revival, transformation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73bcecef46462a8686b11/scaled_640.jpg"
  },
  {
    "title": "From Homeless to Hope: Simon's Journey",
    "genres": "Britpop, Anthemic, Stadium Rock, Melodic Guitar, Powerful Vocals",
    "spiritualMessage": "God's role in success, importance of faith beyond worldly achievements",
    "spiritualNeeds": " Seeking purpose in success, need for eternal perspective, desire to use talents for God",
    "motto": " \"Your story of redemption starts now!\"",
    "keywords": " transformation, purpose, success, faith, redemption, restoration, hope, perseverance, courage, victory, meaning, destiny ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e733bccef46462a86867aa/scaled_640.jpg"
  },
  {
    "title": "Give Jesus a Chance",
    "genres": "Epic cinematic, powerful orchestral, triumphant choirs, dramatic crescendo",
    "spiritualMessage": "Invitation to experience Jesus' transformative love and power",
    "spiritualNeeds": " Skeptical about faith, need for hope, desire for life transformation",
    "motto": " \"The best decision you'll ever make!\"",
    "keywords": " invitation, opportunity, transformation, hope, openness, discovery, experience, change, redemption, renewal, relationship, faith ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e7558ccef46462a8687530/scaled_640.jpg"
  },
  
  {
    "title": "Heaven or Hell: The Choice is Yours",
    "genres": "Epic cinematic, powerful orchestral, triumphant choirs, dramatic crescendo",
    "spiritualMessage": "Urgency of choosing Christ, eternal consequences of decisions",
    "spiritualNeeds": " Facing eternal decisions, need for understanding consequences, desire for salvation",
    "motto": " \"Your eternal address - you decide!\"",
    "keywords": " decision, consequences, eternity, urgency, destiny, future, salvation, opportunity, responsibility, wisdom, accountability, choice ",
    "playlist": "https://www.youtube.com/watch?v=cdijqspVxYE&list=PLck0FjnEKceKhKKQLzOeFTSNZc0FOB0WK",
    "appleMusic": "https://music.apple.com/us/album/heaven-or-hell/1765847561?i=1765847565",
    "spotify": "https://open.spotify.com/album/6xV3RxsM4piih6aG4Tmils",
    "youtube": "https://www.youtube.com/channel/UCKaajesFMCG06biWPe1z1kg",
    "pageUrl": "https://lionheartrevival.com/heaven-or-hell",
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e729ffcef46462a8686309/scaled_640.jpg"
  },
  {
    "title": "Heaven Pass",
    "genres": "drill, fast",
    "spiritualMessage": "Urgency of salvation, importance of being born again, eternal life through Christ",
    "spiritualNeeds": " Urgency for salvation, need for spiritual security, desire for eternal life",
    "motto": " \"Don't miss your flight to eternity!\"",
    "keywords": " salvation, eternity, rebirth, transformation, redemption, hope, future, destiny, opportunity, change, renewal, eternal life ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e7576acef46462a868758f/scaled_640.jpg"
  },
  {
    "title": "Heavenly Visa",
    "genres": "Hip-Hop, trap, Rhythmic spoken word, electronic beats, urgent tone, repetitive hooks",
    "spiritualMessage": "Urgency of salvation, importance of being born again, eternal life through Christ",
    "spiritualNeeds": " Seeking eternal security, need for salvation assurance, desire for heavenly citizenship",
    "motto": " \"Secure your passport to paradise!\"",
    "keywords": " salvation, eternity, rebirth, transformation, redemption, hope, future, destiny, opportunity, change, renewal, eternal life ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e7567dcef46462a868755b/scaled_640.jpg"
  },
  {
    "title": "Highway to Eternity",
    "genres": "Alternative Rock, Spoken Word elements, intense guitar riffs, dramatic pauses, male voice",
    "spiritualMessage": "Life is like a highway leading to eternity; ignoring God's warnings leads to destruction; salvation requires a U-turn towards God",
    "spiritualNeeds": "Need for spiritual direction, desire to avoid eternal destruction, seeking to make life-changing decisions",
    "motto": "\"Make the U-turn of a lifetime - choose your eternal destination!\"",
    "keywords": " life journey, decisions, destiny, direction, purpose, path, choices, consequences, eternity, responsibility, wisdom, meaning ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e757a4cef46462a868759d/scaled_640.jpg"
  },
  {
    "title": "His Footsteps Approach",
    "genres": "Industrial Trap, heavy beats, ominous synths, urgent vocals, apocalyptic tone",
    "spiritualMessage": "Urgency of salvation, signs of Christ's return, need for repentance",
    "spiritualNeeds": " Feeling unprepared for Christ's return, need for spiritual readiness, desire for end-times understanding",
    "motto": " \"The countdown to eternity has begun!\"",
    "keywords": " preparation, urgency, return, repentance, anticipation, readiness, awakening, transformation, renewal, hope, expectation, destiny ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73a9dcef46462a8686a86/scaled_640.jpg"
  },
  {
    "title": "I Know My Redeemer Lives",
    "genres": "Epic cinematic, powerful orchestral, triumphant choirs, dramatic crescendo, G major, BPM 74",
    "spiritualMessage": "Hope in Christ's resurrection, assurance of eternal life",
    "spiritualNeeds": " Facing death or loss, need for hope in resurrection, desire for eternal assurance",
    "motto": " \"Death-defying hope for troubled times!\"",
    "keywords": " hope, assurance, resurrection, eternal life, faith, confidence, victory, redemption, comfort, strength, purpose, future ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e738a3cef46462a868695c/scaled_640.jpg"
  },
  {
    "title": "In God We Trust?",
    "genres": "Epic Cinematic, Powerful Orchestral, Triumphant Choirs, Dramatic Crescendo",
    "spiritualMessage": "Call for genuine faith beyond mere words, living out trust in God",
    "spiritualNeeds": " Questioning faith's relevance, need for genuine trust in God, desire for faith beyond words",
    "motto": " \"From currency to your heart - make it real!\"",
    "keywords": " sincerity, authenticity, faith, actions, integrity, commitment, trust, devotion, genuineness, consistency, living faith, true belief ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73856cef46462a8686955/scaled_640.jpg"
  },
  {
    "title": "In the Heart of Worry",
    "genres": "Acoustic Christian Rock Ballad, Emotional, Intimate",
    "spiritualMessage": "Choosing worship over worry, trusting God in difficult times",
    "spiritualNeeds": " Struggling with anxiety, need for peace, desire to trust God in difficulties",
    "motto": " \"Trade your anxiety for heavenly peace!\"",
    "keywords": " trust, peace, surrender, comfort, faith, assurance, release, calm, hope, strength, confidence, serenity ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e860424ef2856a9219f09b/scaled_512.jpg"
  },
    {
    "title": "In the Silence (Psalm 4)",
    "genres": "Indie Folk, worship, male voice",
    "spiritualMessage": "God is a refuge in dark times; true joy and peace come from trusting in God; God hears and responds to faithful prayers",
    "spiritualNeeds": "Need for inner peace, desire for true joy, seeking refuge from worldly troubles",
    "motto": " \"Find your sanctuary in the silence with God\"",
    "keywords": "Solitude, stillness, meditation, tranquility, rest, contemplation, serenity, quietude, reflection, calm",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e857994ef2856a9219e55c/scaled_512.jpg"
  },
  {
    "title": "Jonah in the Depths",
    "genres": "Biblical opera, prophetic symbolism, dramatic sea journey, opera style, male voice",
    "spiritualMessage": "God's mercy reaches even to the depths; obedience leads to redemption; Jonah's story foreshadows Christ's death and resurrection",
    "spiritualNeeds": "Need for hope in despair, desire for understanding God's bigger plan, seeking redemption from disobedience",
    "motto": "\"Dive into the depths of despair, rise to the heights of grace!\"",
    "keywords": " obedience, mercy, second chance, redemption, repentance, transformation, forgiveness, restoration, purpose, calling, grace, divine plan ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e7453ecef46462a8686ece/scaled_640.jpg"
  },
  {
    "title": "Lost Sheep (Where's Your Shepherd?)",
    "genres": "Modern hip-hop, trap beats, melodic hooks, introspective tone",
    "spiritualMessage": "Warning against worldly distractions, call to follow Jesus as the true Shepherd",
    "spiritualNeeds": " Feeling spiritually lost, need for direction, desire to follow Christ",
    "motto": " \"Find your way back to the divine flock!\"",
    "keywords": " guidance, protection, belonging, return, search, rescue, redemption, restoration, care, love, security, home ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e74868cef46462a868700f/scaled_640.jpg"
  },
  {
    "title": "Marks of Grace",
    "genres": "Epic cinematic, powerful orchestral, triumphant choirs, dramatic crescendo, G major, BPM 74",
    "spiritualMessage": "God's transformative touch, His ability to heal and redeem",
    "spiritualNeeds": " Need for healing from past hurts, desire for transformation, seeking God's touch",
    "motto": " \"Let God rewrite your story!\"",
    "keywords": " healing, redemption, transformation, touch, restoration, renewal, hope, change, mercy, love, divine intervention, new life ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75174cef46462a86873fa/scaled_640.jpg"
  },
  {
    "title": "Mighty God of Hosts",
    "genres": "Powerful worship, strong vocals, building instrumentation, emotional crescendos",
    "spiritualMessage": "Praising God's mighty attributes, calling on His power",
    "spiritualNeeds": " Need for recognition of God's power, desire to trust in God's might, seeking awe in worship",
    "motto": " \"Experience the power of the Divine Commander!\"",
    "keywords": " power, strength, protection, sovereignty, majesty, authority, might, dominion, supremacy, glory, awe, worship ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e85d914ef2856a9219ed54/scaled_512.jpg"
  },
  {
    "title": "Mighty God, We Praise Your Name",
    "genres": "Powerful worship, strong rhythmic vocals, building instrumentation, emotional crescendos",
    "spiritualMessage": "Praising God's mighty attributes, calling on His power and grace",
    "spiritualNeeds": " Desire to praise God, need for recognition of God's attributes, seeking to grow in worship",
    "motto": " \"Join the anthem that shakes the heavens!\"",
    "keywords": " power, praise, attributes, worship, adoration, exaltation, glory, honor, reverence, thanksgiving, majesty, sovereignty ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e85ec84ef2856a9219eeb2/scaled_512.jpg"
  },
  {
    "title": "Monica's Prayer",
    "genres": "Folk ballad, acoustic guitar, piano, gentle percussion, emotive vocals",
    "spiritualMessage": "The power of persistent prayer; a mother's love and faith can change lives; God hears and responds to heartfelt prayers",
    "spiritualNeeds": "Need for hope in seemingly hopeless situations, desire for loved ones' salvation, seeking encouragement in persistent prayer",
    "motto": "\"Your tears of faith can change a destiny!\"",
    "keywords": " perseverance, intercession, faith, motherhood, hope, love, dedication, persistence, trust, answered prayer, transformation, miracle, kids, children, son, daughter",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75ae0cef46462a868769b/scaled_640.jpg"
  },
  {
    "title": "Morning Prayer (Psalm 5)",
    "genres": "Alternative Rock, worship",
    "spiritualMessage": "Trusting in God's guidance and protection, prayer for righteousness",
    "spiritualNeeds": " Need for daily guidance, desire for God's protection, seeking righteousness",
    "motto": " \"Start your day with divine guidance!\"",
    "keywords": " guidance, protection, trust, start of day, direction, strength, hope, faith, peace, preparation, communion, dependence ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e8593f4ef2856a9219e8f4/scaled_512.jpg"
  },
  
   {
    "title": "My King (The Sovereign Lord)",
    "genres": "Epic worship, powerful drums, soaring guitars, choral backing",
    "spiritualMessage": "Jesus is the supreme ruler of all, with unmatched power and love; He meets every human need and is worthy of all praise",
    "spiritualNeeds": "Need for a strong leader, desire for protection and healing, seeking to understand God's supremacy",
    "motto": " \"Encounter the King who reigns over all!\"",
    "keywords": "Majesty, supremacy, omnipotence, ruler, monarch, dominion, authority, throne, scepter, crown",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e85c494ef2856a9219ec12/scaled_512.jpg"
  },
  {
    "title": "Not Just Words",
    "genres": "Emotional Christian rock ballad, heartfelt vocals, building instrumentation, 68 BPM, powerful chorus",
    "spiritualMessage": "Sharing the gospel out of love, not just to win arguments",
    "spiritualNeeds": " Need to share faith effectively, desire to express God's love, seeking to impact others",
    "motto": " \"When actions speak louder than arguments!\"",
    "keywords": " love, sincerity, action, genuine faith, authenticity, commitment, integrity, living faith, impact, transformation, demonstration, true belief ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e86a3d4ef2856a9219fd2a/scaled_512.jpg"
  },
  {
    "title": "Only One",
    "genres": "Contemporary R&B, Gospel-Inspired, Soulful Vocals, Inspirational Lyrics, Spiritual Theme",
    "spiritualMessage": "Jesus as the only Savior, His unique role in salvation and eternity",
    "spiritualNeeds": " Seeking the true Savior, need for assurance in Christ, desire for unique relationship with God",
    "motto": " \"Discover the Savior who stands alone!\"",
    "keywords": " uniqueness, exclusivity, salvation, truth, singularity, supremacy, sufficiency, completeness, necessity, indispensability, irreplaceability, ultimacy ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73142cef46462a8686759/scaled_640.jpg"
  },
  {
    "title": "Pandemic",
    "genres": "Alternative Hip-Hop, spoken word elements, atmospheric synths, minimal percussion, contemplative",
    "spiritualMessage": "Reflecting on the pandemic as a wake-up call to eternal matters",
    "spiritualNeeds": " Seeking meaning in global crisis, need for eternal perspective, desire to understand God's plan",
    "motto": " \"Find hope in the ultimate global crisis!\"",
    "keywords": " reflection, wake-up call, priorities, eternity, mortality, uncertainty, meaning, purpose, faith, resilience, hope, transformation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e7572ecef46462a868758c/scaled_640.jpg"
  },
  {
    "title": "Passage Through the Sea",
    "genres": "Epic biblical oratorio, dramatic choral pieces, powerful solos, and grand orchestral interludes depicting the Exodus",
    "spiritualMessage": "God's deliverance and faithfulness, trust in His power",
    "spiritualNeeds": " Facing impossible situations, need for faith in God's power, desire for deliverance",
    "motto": " \"Walk through your impossible with God!\"",
    "keywords": " deliverance, faithfulness, trust, miracles, liberation, protection, divine intervention, hope, victory, courage, faith, transformation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73c84cef46462a8686ba9/scaled_640.jpg"
  },
  {
    "title": "Praise the Lord (Psalm 117)",
    "genres": "Modern Worship, driving guitar, powerful drums, dynamic keyboard, passionate lead vocals, chorus",
    "spiritualMessage": "Call to praise God, His faithfulness to all nations",
    "spiritualNeeds": " Need for joyful praise, desire to recognize God's faithfulness, seeking to worship with all nations",
    "motto": " \"Join the global chorus of praise!\"",
    "keywords": " worship, gratitude, universality, faithfulness, adoration, exaltation, glory, honor, thanksgiving, joy, celebration, reverence ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e8599e4ef2856a9219e960/scaled_512.jpg"
  },
  
  {
    "title": "Real Talk",
    "genres": "hip-hop, rap, trap",
    "spiritualMessage": "Urgency of salvation, Christ's sacrifice, choice between heaven and hell",
    "spiritualNeeds": " Need for straightforward gospel message, desire for clear choices, seeking understanding of salvation",
    "motto": " \"No sugar-coating - just soul-saving truth!\"",
    "keywords": " urgency, sacrifice, decision, eternity, truth, reality, consequences, choice, salvation, destiny, accountability, transformation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e750f1cef46462a86873d8/scaled_640.jpg"
  },
  {
    "title": "Refuge in the Storm",
    "genres": "Cinematic Rock, Epic, Intense",
    "spiritualMessage": "God as refuge in end times, urgency of salvation through Christ",
    "spiritualNeeds": " Seeking safety in troubling times, need for God's protection, desire for end-times preparation",
    "motto": " \"Find shelter in the ultimate safe house!\"",
    "keywords": " protection, safety, end times, trust, security, shelter, comfort, peace, strength, hope, assurance, faith ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73e8acef46462a8686c13/scaled_640.jpg"
  },
  {
    "title": "Reluctant Prophet",
    "genres": "Biblical musical, Broadway style, comedic elements, dramatic sea scenes, divine interventions, male voice",
    "spiritualMessage": "God's mercy extends to all, even those we deem unworthy; obedience to God's call is crucial; God's compassion surpasses human understanding",
    "spiritualNeeds": "Need for understanding God's universal love, desire to overcome prejudice, seeking to align with God's will despite personal reservations",
    "motto": "\"Dive into a whale of a tale about God's boundless mercy!\"",
    "keywords": " obedience, mercy, compassion, second chances, calling, purpose, divine plan, transformation, forgiveness, redemption, mission, surrender ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e74039cef46462a8686cb9/scaled_640.jpg"
  },
  {
    "title": "Remember Your Creator",
    "genres": "Post-Rock, ballad, emotional vocals, piano, strings, orchestral climax",
    "spiritualMessage": "Importance of remembering God in youth, fleeting nature of life",
    "spiritualNeeds": " Youth seeking purpose, need for life direction, desire to honor God early in life",
    "motto": " \"Youth + Faith = Unbeatable Combination!\"",
    "keywords": " youth, meaning, purpose, time, priorities, wisdom, direction, foundation, eternity, legacy, accountability, life choices ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75134cef46462a86873da/scaled_640.jpg"
  },
  
  
  {
    "title": "The Ancient Tale of Liberation",
    "genres": "Epic folk ballad, acoustic guitar, Celtic harp, subtle percussion, ethereal vocals, haunting flute",
    "spiritualMessage": "God's redemptive plan through Christ, from bondage to freedom",
    "spiritualNeeds": " Seeking freedom from spiritual bondage, need for understanding God's redemptive plan, desire for liberation in Christ",
    "motto": " \"Break free from the chains you can't see!\"",
    "keywords": " redemption, freedom, rescue, deliverance, salvation, liberation, hope, transformation, restoration, victory, divine intervention, new beginning ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e7595acef46462a8687620/scaled_640.jpg"
  },
  {
    "title": "The Conqueror of Death",
    "genres": "Epic Celtic folk ballad, acoustic guitar, harp, flute, ethereal vocals",
    "spiritualMessage": "Christ's victory over death, hope in resurrection",
    "spiritualNeeds": " Facing fear of death, need for hope in resurrection, desire for victory over mortality",
    "motto": " \"Meet the ultimate superhero - death's worst enemy!\"",
    "keywords": " victory, resurrection, hope, eternal life, triumph, power, redemption, transformation, new life, assurance, faith, salvation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75a4acef46462a868764e/scaled_640.jpg"
  },
  {
    "title": "The Day the Sun Stood Still",
    "genres": "Epic biblical oratorio, majestic orchestration, powerful solos and grand choral pieces",
    "spiritualMessage": "God's power over creation, faithfulness to His people",
    "spiritualNeeds": " Need for faith in God's power, desire for miraculous intervention, seeking courage in impossible situations",
    "motto": " \"Witness the day time stood still for God!\"",
    "keywords": " miracles, power, faithfulness, impossibilities, divine intervention, supernatural, faith, victory, assurance, trust, providence, sovereignty ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73ae8cef46462a8686ad0/scaled_640.jpg"
  },
  {
    "title": "The Deliverance of Jerusalem",
    "genres": "Classical oratorio, epic biblical narrative, orchestral grandeur, dramatic solo and choral parts",
    "spiritualMessage": "God's deliverance of His people, His power over enemies",
    "spiritualNeeds": " Facing overwhelming odds, need for trust in God's deliverance, desire for victory over enemies",
    "motto": " \"When God fights your battles, victory is assured!\"",
    "keywords": " protection, rescue, faithfulness, victory, deliverance, divine intervention, hope, salvation, trust, power, providence, triumph ",
    "playlist": "https://www.youtube.com/playlist?list=PLck0FjnEKceJoucos8aafA0K87DWJRk1V",
    "appleMusic": "https://music.apple.com/us/album/the-deliverance-of-jerusalem-single/1767226507",
    "spotify": "https://open.spotify.com/album/6AEerYv7rDdRGvUwMyasvS",
    "youtube": "https://youtu.be/oEfVgoTvr6A",
    "pageUrl": "https://lionheartrevival.com/the-deliverance-of-jerusalem",
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e72c42cef46462a8686469/scaled_640.jpg"
  },
  {
    "title": "The Divine Mirror",
    "genres": "Sacred Oratorio",
    "spiritualMessage": "God's holiness, human sinfulness, call to repentance",
    "spiritualNeeds": " Need for self-reflection, desire for holiness, seeking repentance",
    "motto": " \"See yourself through God's eyes!\"",
    "keywords": " holiness, reflection, transformation, repentance, self-examination, truth, change, renewal, purification, sanctification, growth, revelation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73f6bcef46462a8686c67/scaled_640.jpg"
  },
  {
    "title": "The Fourth in the Fire",
    "genres": "Epic biblical ballad, orchestral backing, powerful vocals, dramatic narrative style",
    "spiritualMessage": "God's protection in trials, faithfulness in persecution",
    "spiritualNeeds": " Facing persecution for faith, need for courage, desire for God's protection in trials",
    "motto": " \"Stand firm - you're fireproof in faith!\"",
    "keywords": " protection, faithfulness, trials, deliverance, courage, divine presence, trust, victory, supernatural, faith, testimony, miracle ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73d24cef46462a8686bc2/scaled_640.jpg"
  },
  {
    "title": "The Grace, Love, and Communion",
    "genres": "Christian Pop, Vocal Pop, Contemporary Christian, Country, Soft Rock, Majestic worship",
    "spiritualMessage": "Trinity's blessing, God's grace, love, and fellowship",
    "spiritualNeeds": " Seeking understanding of Trinity, need for God's blessings, desire for divine fellowship",
    "motto": " \"Experience the Trinity's embrace!\"",
    "keywords": " trinity, blessing, fellowship, relationship, unity, harmony, divine attributes, intimacy, connection, community, love, grace ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e85b414ef2856a9219eb24/scaled_512.jpg"
  },
  {
    "title": "The Great Disappearance",
    "genres": "Cinematic Industrial Trap, epic orchestral, intense beats, dramatic vocals",
    "spiritualMessage": "Rapture, urgency of salvation, Christ's return",
    "spiritualNeeds": " Seeking understanding of end times, need for preparedness for Christ's return, desire for assurance of salvation",
    "motto": " \"Will you be left behind?\"",
    "keywords": " rapture, preparation, urgency, return, end times, anticipation, readiness, eternity, transformation, hope, salvation, reunion ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e72ff1cef46462a86866a0/scaled_640.jpg"
  },
  {
    "title": "The Heavens Declare (Celestial Prophecy)",
    "genres": "Epic folk ballad, acoustic guitar, Celtic harp, subtle percussion, ethereal vocals",
    "spiritualMessage": "God's glory revealed in creation, His redemptive plan",
    "spiritualNeeds": " Seeking God in nature, need for understanding God's plan, desire to see God's glory in creation",
    "motto": " \"Read God's message written in the stars!\"",
    "keywords": " creation, revelation, plan, purpose, divine design, cosmic message, testimony, glory, wisdom, power, beauty, wonder ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e759d3cef46462a868762b/scaled_640.jpg"
  },
  {
    "title": "The Humbling of a King",
    "genres": "Epic historical ballad, oratorio, orchestral backing, dramatic vocals, with biblical narrative",
    "spiritualMessage": "God's sovereignty, danger of pride, importance of humility",
    "spiritualNeeds": " Struggling with pride, need for humility, desire to recognize God's sovereignty",
    "motto": " \"Pride goes before a fall - learn from a king!\"",
    "keywords": " pride, humility, sovereignty, repentance, transformation, lesson, divine discipline, restoration, wisdom, accountability, change, redemption ",
    "playlist": null,
    "appleMusic": "https://music.apple.com/us/album/the-humbling-of-a-king-single/1767035630?uo=4&app=music&at=1001lry3&ct=dashboard",
    "spotify": "https://open.spotify.com/album/3z5iftccHofo1LWTKBxRS4",
    "youtube": "https://www.youtube.com/watch?v=eZwuOYYtTJI",
    "pageUrl": "https://lionheartrevival.com/the-humbling-of-a-king",
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e725b4cef46462a86860b3/scaled_640.jpg"
  },
  {
    "title": "The Journey of Purpose",
    "genres": "Soft rock ballad, acoustic guitar, piano, gentle percussion, harmonizing vocals",
    "spiritualMessage": "Finding life's purpose in God, eternal perspective",
    "spiritualNeeds": " Seeking life's purpose, need for meaning, desire to align with God's plan",
    "motto": " \"Navigate life with divine GPS!\"",
    "keywords": " meaning, destiny, eternal perspective, calling, direction, significance, fulfillment, mission, legacy, growth, discovery, transformation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e758a2cef46462a86875ed/scaled_640.jpg"
  },
  {
    "title": "The Last Word",
    "genres": "Emotive rock ballad, powerful vocals, piano, building to full band climax",
    "spiritualMessage": "Trust in God's sovereignty, His final say in all matters",
    "spiritualNeeds": " Facing uncertainties, need for trust in God's control, desire for peace in God's sovereignty",
    "motto": " \"Spoiler alert: God wins!\"",
    "keywords": " sovereignty, trust, final authority, assurance, confidence, faith, surrender, acceptance, peace, hope, security, divine control ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e754c0cef46462a86874fc/scaled_640.jpg"
  },
  {
    "title": "The Lord's Anointed (Psalm 2 Rock Anthem) ",
    "genres": "Epic Christian Rock, electric guitars, powerful drums, orchestral elements, worship, gospel, male voice",
    "spiritualMessage": "God's sovereignty over earthly rulers, futility of rebelling against God, blessing of trusting in God's anointed Son",
    "spiritualNeeds": "Feeling powerless against worldly authorities, need for assurance of God's ultimate control, desire to align with God's plan",
    "motto": "\"Rock out to the anthem of divine sovereignty!\"",
    "keywords": " authority, rebellion, trust, blessing, sovereignty, power, victory, submission, divine rule, protection, destiny, triumph ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e7340dcef46462a86867b8/scaled_640.jpg"
  },
  {
    "title": "The Might of God",
    "genres": "Gospel,Contemporary Christian,Worship,Ethereal,Emotional,Intimate,Majestic,Cinematic",
    "spiritualMessage": "God's power and might, call to praise and trust Him",
    "spiritualNeeds": " Need for recognition of God's power, desire to trust in difficult times, seeking awe of God",
    "motto": " \"Tap into unlimited divine power!\"",
    "keywords": " power, strength, trust, praise, sovereignty, majesty, awe, worship, confidence, security, glory, exaltation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e85bf64ef2856a9219ebad/scaled_512.jpg"
  },
  
  {
    "title": "The Name",
    "genres": "Pop Rock, worship elements, electric guitar riffs, driving drums, passionate vocals, chorus, male voice",
    "spiritualMessage": "Jesus is unique among religious figures; His name has power and provokes reaction; He is the only way to salvation",
    "spiritualNeeds": "Need for boldness in faith, desire to understand Jesus' uniqueness, seeking assurance in Christ as the only Savior",
    "motto": "\"Shout the name that shakes the universe!\"",
    "keywords": " uniqueness, power, salvation, reaction, authority, transformation, hope, identity, reverence, worship, redemption, truth ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73dedcef46462a8686bec/scaled_640.jpg"
  },
  {
    "title": "The One Answer",
    "genres": "Epic cinematic, powerful orchestral, triumphant choirs, dramatic crescendo",
    "spiritualMessage": "Jesus as the answer to all needs, invitation to trust Him",
    "spiritualNeeds": " Seeking solutions to life's problems, need for direction, desire for completeness in Christ",
    "motto": " \"Solve life's puzzle with the missing piece!\"",
    "keywords": " solution, hope, trust, invitation, salvation, completeness, sufficiency, truth, transformation, redemption, peace, fulfillment ",
    "playlist": "https://www.youtube.com/watch?v=NA80dYZHVGY&list=PLck0FjnEKceKhKKQLzOeFTSNZc0FOB0WK",
    "appleMusic": "https://music.apple.com/us/album/the-one-answer-single/1767134856",
    "spotify": "https://open.spotify.com/album/2OaHgkJLshIEHm06klt5g0",
    "youtube": "https://youtu.be/NA80dYZHVGY",
    "pageUrl": "https://lionheartrevival.com/the-one-answer",
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75e4dcef46462a86877a5/scaled_640.jpg"
  },
  {
    "title": "The Prophet's Burden",
    "genres": "Epic rock ballad, powerful vocals, electric guitar, orchestral elements, dramatic",
    "spiritualMessage": "Prophet's calling, rejection by people, God's faithfulness",
    "spiritualNeeds": " Feeling misunderstood in faith, need for perseverance in God's calling, desire to speak truth despite rejection",
    "motto": " \"Carry the weight of divine truth!\"",
    "keywords": " calling, rejection, faithfulness, perseverance, mission, courage, conviction, divine message, obedience, purpose, endurance, truth ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75bd3cef46462a86876f8/scaled_640.jpg"
  },
  {
    "title": "The Questions That Matter",
    "genres": "Epic rap, powerful beat, orchestral backing, cinematic elements, gospel choir, 80-85 BPM, emotional",
    "spiritualMessage": "Urgency of salvation, God's love, importance of choosing Christ",
    "spiritualNeeds": " Seeking answers to life's big questions, need for salvation, desire for eternal security",
    "motto": " \"Answers to life's biggest questions!\"",
    "keywords": " urgency, love, decision, salvation, eternity, purpose, meaning, destiny, truth, priorities, accountability, transformation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e7548fcef46462a86874f8/scaled_640.jpg"
  },
  {
    "title": "The Real God",
    "genres": "Conscious Hip-Hop, hard-hitting beats, soulful samples, introspective flow, 90 BPM",
    "spiritualMessage": "Challenging misconceptions about God, His true nature and judgment",
    "spiritualNeeds": " Questioning misconceptions about God, need for true understanding of God's nature, desire for genuine relationship with God",
    "motto": " \"Meet the God beyond your imagination!\"",
    "keywords": " misconceptions, truth, judgment, nature, revelation, understanding, authenticity, reality, divine attributes, discernment, wisdom, knowledge ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75994cef46462a8687623/scaled_640.jpg"
  },
  
  {
    "title": "The Scales of Eternity",
    "genres": "Symphonic Metal, 140 bpm",
    "spiritualMessage": "God's judgment, urgency of choosing Christ, eternal consequences",
    "spiritualNeeds": " Facing judgment, need for eternal perspective, desire for righteous living",
    "motto": " \"What's your soul's true weight?\"",
    "keywords": " judgment, decision, consequences, urgency, accountability, eternity, choices, destiny, responsibility, truth, justice, salvation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e730c0cef46462a8686720/scaled_640.jpg"
  },
  {
    "title": "The Shepherd's Faith",
    "genres": "Epic biblical oratorio, heroic orchestration, powerful solos and triumphant choral pieces",
    "spiritualMessage": "Faith in God's power, victory through trust in Him",
    "spiritualNeeds": " Facing giants in life, need for courage, desire to trust God's power",
    "motto": " \"Slay your giants with shepherd-sized faith!\"",
    "keywords": " trust, victory, power, confidence, guidance, protection, provision, care, assurance, hope, courage, reliance ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e72eabcef46462a86865e2/scaled_640.jpg"
  },
  {
    "title": "The Teapot and the Truth",
    "genres": "Epic Christian rock, powerful vocals, orchestral backdrop, 75 BPM, thought-provoking lyrics",
    "spiritualMessage": "God's existence versus atheist arguments, importance of faith",
    "spiritualNeeds": " Dealing with doubts about God's existence, need for faith beyond logic, desire for spiritual truth",
    "motto": " \"Brew a fresh pot of faith!\"",
    "keywords": " existence, faith, arguments, belief, evidence, reason, truth, debate, understanding, conviction, discovery, revelation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e7521fcef46462a868744d/scaled_640.jpg"
  },
  {
    "title": "The Test of Time",
    "genres": "Contemporary Christian Rock, electric guitar riffs, driving drums, melodic bass lines, emotive vocal",
    "spiritualMessage": "Life as a test, importance of faith, eternity's significance",
    "spiritualNeeds": " Seeking life's meaning, need for eternal perspective, desire to live for God",
    "motto": " \"Ace the exam of eternity!\"",
    "keywords": " life purpose, faith, eternity, significance, meaning, legacy, endurance, perseverance, truth, values, priorities, destiny ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e751e4cef46462a868743e/scaled_640.jpg"
  },
  {
    "title": "The Torches of Faith: Gideon and the 300",
    "genres": "Epic biblical battle oratorio, triumphant choruses, doubt-to-faith solos, and dramatic orchestral interludes",
    "spiritualMessage": "God's power through faith, victory through obedience",
    "spiritualNeeds": " Feeling inadequate, need for courage, desire to trust God's power in weakness",
    "motto": " \"Small army, big God - unbeatable combo!\"",
    "keywords": " courage, obedience, victory, unlikely heroes, faith, trust, divine strategy, empowerment, transformation, mission, calling, triumph ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e86cdb4ef2856a921a010c/scaled_512.jpg"
  },
  {
    "title": "The True Source of Greatness",
    "genres": "Epic Cinematic, Powerful Orchestral, Triumphant Choirs, Dramatic Crescendo",
    "spiritualMessage": "True greatness comes from God, not human achievements or political slogans",
    "spiritualNeeds": " Seeking true greatness, need for humility, desire to align with God's standards",
    "motto": " \"Redefine greatness with divine standards!\"",
    "keywords": " humility, true success, divine origin, purpose, significance, meaning, identity, worth, value, destiny, calling, fulfillment ",
    "playlist": "https://www.youtube.com/watch?v=LdqA8UXw2hU&list=PLck0FjnEKceJLNBcct6CwFpTgsahwfIgU",
    "appleMusic": "https://music.apple.com/me/album/the-true-source-of-greatness-single/1765683771",
    "spotify": "https://open.spotify.com/track/5nlGXivMSslGN8lom128pc",
    "youtube": "https://youtu.be/LdqA8UXw2hU",
    "pageUrl": "https://lionheartrevival.com/the-true-source-of-greatness",
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75e85cef46462a86877a8/scaled_640.jpg"
  },
  {
    "title": "The Ultimate Rock",
    "genres": "Epic Christian Rock, electric guitars, powerful drums, orchestral elements, worship, gospel",
    "spiritualMessage": "Jesus as the ultimate answer and foundation for life",
    "spiritualNeeds": " Seeking stability in life, need for strong foundation, desire for assurance in Christ",
    "motto": " \"Build your life on unshakeable ground!\"",
    "keywords": " foundation, answer, stability, truth, security, reliability, strength, assurance, confidence, faith, dependability, cornerstone ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e72f3ecef46462a868663f/scaled_640.jpg"
  },
  {
    "title": "The Unshakeable Kingdom",
    "genres": "cinematic, symphony, ballad, acoustic guitar, piano, gentle strings, reflective tone",
    "spiritualMessage": "God's eternal kingdom, futility of earthly empires, citizenship in heaven",
    "spiritualNeeds": " Feeling insecure in changing world, need for eternal perspective, desire for citizenship in God's kingdom",
    "motto": " \"Citizenship in the only lasting empire!\"",
    "keywords": " eternity, citizenship, stability, permanence, security, hope, future, belonging, purpose, destiny, glory, triumph ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73cd5cef46462a8686bb0/scaled_640.jpg"
  },
  {
    "title": "The Unspoken Truth",
    "genres": "Contemporary Christian Music, Soft Rock, reflective tone, gentle guitar, emotive vocals, 72 BPM",
    "spiritualMessage": "Reality of heaven and hell, importance of faith in Christ for eternity",
    "spiritualNeeds": " Need for understanding eternal consequences, desire for salvation, seeking truth about afterlife",
    "motto": " \"Hear the message heaven's been dying to tell you!\"",
    "keywords": " afterlife, eternity, faith, reality, consequences, destiny, urgency, salvation, truth, revelation, awakening, eternity ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75c3bcef46462a8687701/scaled_640.jpg"
  },
  {
    "title": "The Voice That Shatters Death",
    "genres": "Epic rock ballad, powerful guitars, dramatic drums, emotional vocals",
    "spiritualMessage": "Christ's power over death, hope in resurrection",
    "spiritualNeeds": " Facing fear of death, need for hope in resurrection, desire for victory over mortality",
    "motto": " \"Death's worst nightmare - your greatest hope!\"",
    "keywords": " power, resurrection, hope, victory, life, transformation, triumph, authority, salvation, eternity, redemption, conquest ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73c2dcef46462a8686b32/scaled_640.jpg"
  },
  {
    "title": "The Void Within",
    "genres": "Industrial Trap, heavy beats, ominous synths, urgent vocals, apocalyptic tone",
    "spiritualMessage": "Only God can fill the emptiness in human hearts, need for Christ",
    "spiritualNeeds": " Feeling empty inside, need for fulfillment, desire for God's presence",
    "motto": " \"Fill the God-shaped hole in your heart!\"",
    "keywords": " emptiness, fulfillment, purpose, satisfaction, meaning, completeness, wholeness, peace, contentment, joy, transformation, redemption ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e756efcef46462a868756f/scaled_640.jpg"
  },
  {
    "title": "The Wall of Sin",
    "genres": "Cinematic Industrial Trap, epic orchestral, intense beats, dramatic vocals, 75 BPM",
    "spiritualMessage": "Sin's separation from God, Christ's sacrifice as the solution",
    "spiritualNeeds": " Struggling with sin, need for forgiveness, desire for reconciliation with God",
    "motto": " \"Tear down the barrier between you and God!\"",
    "keywords": " separation, barrier, solution, reconciliation, redemption, restoration, healing, forgiveness, hope, transformation, reunion, breakthrough ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75916cef46462a8687619/scaled_640.jpg"
  },
  {
    "title": "The Wise Man's Conclusion",
    "genres": "Cinematic symphonic, epic orchestral, choral elements, dramatic build-up, male voice",
    "spiritualMessage": "The song echoes Ecclesiastes, emphasizing the importance of fearing God and keeping His commandments.\t",
    "spiritualNeeds": "Need for life's purpose, desire for wisdom, seeking accountability and direction in life",
    "motto": "\"Discover the timeless secret to a meaningful life!\"",
    "keywords": " wisdom, purpose, judgment, meaning, priorities, fear of God, obedience, accountability, fulfillment, legacy, truth, understanding ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e752c8cef46462a868746e/scaled_640.jpg"
  },
  {
    "title": "The Word Slips Away",
    "genres": "Epic cinematic, powerful orchestral, triumphant choirs, dramatic crescendo",
    "spiritualMessage": "The ultimate wisdom is to fear God and keep His commandments; all actions will be judged by God; true meaning in life comes from following God's ways",
    "spiritualNeeds": " Neglecting Bible study, need for spiritual nourishment, desire to value God's Word",
    "motto": " \"Don't let eternal wisdom slip through your fingers!\"",
    "keywords": " wisdom, obedience, judgment, meaning, accountability, truth, priorities, consequences, eternity, legacy, purpose, divine guidance ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e756b3cef46462a8687561/scaled_640.jpg"
  },
  {
    "title": "The Words Unspoken",
    "genres": "Epic Cinematic, Powerful Orchestral, Triumphant Choirs, Dramatic Crescendo",
    "spiritualMessage": "Urgency of salvation, reality of judgment, importance of faith in Christ",
    "spiritualNeeds": " Need for understanding judgment, desire for salvation, seeking eternal security",
    "motto": " \"Hear the verdict before the final trial!\"",
    "keywords": " urgency, judgment, faith, salvation, truth, revelation, eternity, consequences, decision, awakening, transformation, redemption ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e75a08cef46462a868763c/scaled_640.jpg"
  },
  {
    "title": "Tick Tock",
    "genres": "hip hop, Spoken word, electronic beats, dramatic sound effects, urgent rhythm",
    "spiritualMessage": "Urgency of salvation, eternal consequences of choices",
    "spiritualNeeds": " Feeling urgency of life decisions, need for salvation, desire for eternal perspective",
    "motto": " \"Your soul's countdown - don't waste a second!\"",
    "keywords": " urgency, time, decisions, eternity, countdown, choices, consequences, destiny, opportunity, moment, action, salvation ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e750a5cef46462a86873b0/scaled_640.jpg"
  },
 
  {
    "title": "True Treasure",
    "genres": "Soft rock ballad, acoustic guitar, piano, gentle strings, emotive vocals",
    "spiritualMessage": "The most valuable treasure is a repentant heart seeking God's forgiveness; earthly riches are temporary, but spiritual wealth is eternal",
    "spiritualNeeds": "Seeking true fulfillment, need for perspective on material wealth, desire for spiritual transformation",
    "motto": "\"Discover the treasure that makes heaven sing!\"",
    "keywords": " values, priorities, forgiveness, eternal wealth, significance, meaning, heavenly riches, true worth, spiritual investment, lasting legacy, heart transformation, eternal perspective ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73530cef46462a86867fe/scaled_640.jpg"
  },
  
  {
    "title": "Unshakeable (Psalm 3)",
    "genres": "Alternative Rock, Worship Rock, worship, male voice",
    "spiritualMessage": "God provides unshakeable strength and protection in the face of enemies and fears; trust in God leads to peace and confidence",
    "spiritualNeeds": "Need for strength in adversity, desire for peace amid turmoil, seeking divine protection and confidence",
    "motto": " \"Become unshakeable in a world of chaos!\"",
    "keywords": "Steadfast, resilient, fortress, secure, fearless, surrounded, perseverance, triumph, restoration, invincible",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e852f14ef2856a9219dd5e/scaled_512.jpg"
  },

  {
    "title": "Unshaken Faith: Daniel in the Lions' Den",
    "genres": "Biblical epic oratorio, dramatic solos, angelic choruses, and triumphant finale celebrating divine deliverance",
    "spiritualMessage": "God's faithfulness in trials, courage in faith, divine protection",
    "spiritualNeeds": " Facing persecution, need for courage in faith, desire for God's protection",
    "motto": " \"Face your lions with lion-tamer faith!\"",
    "keywords": " courage, protection, faithfulness, deliverance, trust, divine intervention, perseverance, testimony, miracle, victory, steadfastness, conviction ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e738e5cef46462a8686989/scaled_640.jpg"
  },
  {
    "title": "Valor and Sacrifice",
    "genres": "Epic biblical oratorio, heroic orchestration, powerful solos and triumphant choral pieces",
    "spiritualMessage": "Courage in serving God, sacrificial love, God's power through faithful servants",
    "spiritualNeeds": " Need for courage in serving God, desire to live sacrificially, seeking to make a difference for God",
    "motto": " \"Become a hero in God's epic saga!\"",
    "keywords": " courage, service, love, faithfulness, dedication, commitment, selflessness, heroism, devotion, purpose, calling, mission ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73055cef46462a86866da/scaled_640.jpg"
  },
 
  {
    "title": "Walls of Faith: The Fall of Jericho",
    "genres": "Epic biblical battle oratorio, contrasting quiet marches with triumphant fanfares, powerful choruses, male voice",
    "spiritualMessage": "God's power overcomes impossible obstacles; faith and obedience lead to victory; God's timing and methods may be unconventional but are always effective",
    "spiritualNeeds": "Facing seemingly insurmountable challenges, need for faith in God's promises, desire for victory through unconventional spiritual warfare",
    "motto": "\"March around your Jericho - faith brings walls down!\"",
    "keywords": " obstacles, victory, obedience, unconventional methods, faith, trust, divine strategy, breakthrough, miracles, impossibilities, triumph, power ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73769cef46462a868690e/scaled_512.jpg"
  },
  {
    "title": "Watchman's Call",
    "genres": "Dramatic Rock Ballad, Prophetic, Intense, 80 bpm",
    "spiritualMessage": "Urgency of spiritual awakening, signs of the times, call to prepare for Christ's return",
    "spiritualNeeds": " Need for spiritual vigilance, desire to understand end times, seeking to prepare for Christ's return",
    "motto": " \"Stay alert - eternity is on the horizon!\"",
    "keywords": " awakening, preparation, signs, return, vigilance, readiness, urgency, prophecy, warning, discernment, spiritual alertness, end times ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e73d62cef46462a8686bcc/scaled_640.jpg"
  },
  
 
  {
    "title": "World Gone Mad",
    "genres": "Alternative Rock, Post-Hardcore, Emotional Rock Ballad, electric guitar, piano, strings, powerful drums, passionate, dynamic build-up, male voice",
    "spiritualMessage": "In a chaotic world, hope and sanity are found in God; trusting in God provides protection and direction amid life's challenges",
    "spiritualNeeds": "Need for stability in a chaotic world, desire for hope amid despair, seeking divine protection and guidance",
    "motto": "\"Find your sanity in an insane world - choose God's path!\"",
    "keywords": " chaos, sanity, protection, direction, hope, stability, divine order, peace, guidance, refuge, assurance, faith ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e755c4cef46462a8687534/scaled_640.jpg"
  },
  {
    "title": "Why So Downcast?",
    "genres": "Epic cinematic, orchestral swells, choral backing, dramatic percussion",
    "spiritualMessage": "Encouragement to trust God in times of despair, hope in God's faithfulness",
    "spiritualNeeds": " Dealing with depression or discouragement, need for hope, desire to trust God in dark times",
    "motto": " \"Lift your spirit with heaven's hope!\"",
    "keywords": " encouragement, trust, hope, faithfulness, uplift, comfort, reassurance, strength, renewal, perspective, joy, confidence ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e8561e4ef2856a9219e32b/scaled_512.jpg"
  },
  {
    "title": "Your Heavenly Pass",
    "genres": "Cinematic Rock, Epic, Intense, 75 bpm",
    "spiritualMessage": "Urgency of salvation, importance of being \"born again\", preparing for eternity",
    "spiritualNeeds": " Seeking assurance of salvation, need for eternal security, desire to prepare for eternity",
    "motto": " \"Don't be left at heaven's gates!\"",
    "keywords": " salvation, rebirth, preparation, eternity, transformation, hope, destiny, redemption, heavenly citizenship, assurance, eternal life, divine acceptance ",
    "playlist": null,
    "appleMusic": null,
    "spotify": null,
    "youtube": null,
    "pageUrl": null,
    "coverImage": "https://d3flpus5evl89n.cloudfront.net/66e714e4cef46462a8685874/66e758e1cef46462a86875fd/scaled_640.jpg"
  }
  
  ];
